//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_Management.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Attendance_Management.Services.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de area ya existe..
        /// </summary>
        internal static string AreaCodeDuplicate {
            get {
                return ResourceManager.GetString("AreaCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El area ingresada no existe..
        /// </summary>
        internal static string AreaNotFound {
            get {
                return ResourceManager.GetString("AreaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro el Id del area y puesto.
        /// </summary>
        internal static string AreasUserNotFound {
            get {
                return ResourceManager.GetString("AreasUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede inserta un horario con una hora de salida menor o igual a la hora de entrada..
        /// </summary>
        internal static string CheckOutError {
            get {
                return ResourceManager.GetString("CheckOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se proporciono un formato valido para la busqueda..
        /// </summary>
        internal static string DateTimeFormatInvalid {
            get {
                return ResourceManager.GetString("DateTimeFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código del deparmento ya existe..
        /// </summary>
        internal static string DepartmentCodeDuplicated {
            get {
                return ResourceManager.GetString("DepartmentCodeDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento no encontrado..
        /// </summary>
        internal static string DepartmentNotFound {
            get {
                return ResourceManager.GetString("DepartmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este correo no está asociado a ningún empleado.
        /// </summary>
        internal static string EmpCodeNotFound {
            get {
                return ResourceManager.GetString("EmpCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se  encontro al empleado..
        /// </summary>
        internal static string EmployeeNotFound {
            get {
                return ResourceManager.GetString("EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El objecto se encuentra vacío..
        /// </summary>
        internal static string EmptyObject {
            get {
                return ResourceManager.GetString("EmptyObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro la configuration..
        /// </summary>
        internal static string GeneralConfigurationNotFound {
            get {
                return ResourceManager.GetString("GeneralConfigurationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro ningun dia inhábil..
        /// </summary>
        internal static string HolidayNotFound {
            get {
                return ResourceManager.GetString("HolidayNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha inicial posterior a la fecha final..
        /// </summary>
        internal static string InitialDateError {
            get {
                return ResourceManager.GetString("InitialDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error interno del servidor..
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe la vista a la que se intenta acceder..
        /// </summary>
        internal static string NoExistsView {
            get {
                return ResourceManager.GetString("NoExistsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código del puesto ya existe..
        /// </summary>
        internal static string PositionCodeDuplicated {
            get {
                return ResourceManager.GetString("PositionCodeDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El puesto ingresado no existe..
        /// </summary>
        internal static string PositionNotFound {
            get {
                return ResourceManager.GetString("PositionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se elimino el Rol.
        /// </summary>
        internal static string RolNotDelete {
            get {
                return ResourceManager.GetString("RolNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro el usuario..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no tiene asigno un rol..
        /// </summary>
        internal static string UserRolNotFound {
            get {
                return ResourceManager.GetString("UserRolNotFound", resourceCulture);
            }
        }
    }
}
